// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG4JgKcHP4TVlB5w_tIgeDGTzNkM7sCBQ',
    appId: '1:925969828172:web:d5ab5832bf5f60b589a7e9',
    messagingSenderId: '925969828172',
    projectId: 'fpcl-ops',
    authDomain: 'fpcl-ops.firebaseapp.com',
    storageBucket: 'fpcl-ops.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy9VkyDbD0DLw4yNe7idj1jgrjmDS1kUc',
    appId: '1:925969828172:android:59567409f2c4e58c89a7e9',
    messagingSenderId: '925969828172',
    projectId: 'fpcl-ops',
    storageBucket: 'fpcl-ops.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGkqH9UvI2WpEBblX2IADMmHQ-IOewNvg',
    appId: '1:925969828172:ios:a748411a5f7bb2f489a7e9',
    messagingSenderId: '925969828172',
    projectId: 'fpcl-ops',
    storageBucket: 'fpcl-ops.firebasestorage.app',
    iosBundleId: 'com.example.superoperator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG4JgKcHP4TVlB5w_tIgeDGTzNkM7sCBQ',
    appId: '1:925969828172:web:d0df47a783dc029589a7e9',
    messagingSenderId: '925969828172',
    projectId: 'fpcl-ops',
    authDomain: 'fpcl-ops.firebaseapp.com',
    storageBucket: 'fpcl-ops.firebasestorage.app',
  );
}
